### ISSUE TITLE
AttributeError: module 'pydivert' has no attribute 'WinDivert'

### ISSUE THREAD

**Issue by ArijitM10** [ffalcinelli/pydivert#31]
I installed latest version of pydivert 2.1.0 . As per installation process it's mentioned Windivert will be inbuilt with this library, but I'm getting the above mentioned exception. 
Python version - 3.6.4

**Comment by ffalcinelli** [comment]
Yes WinDivert is bundled, this means the .dll and .sys files are installed among the pydivert binding itself. What you're getting is a python attribute error, could you share a piece of code? Especially the import statement.

**Comment by ArijitM10** [comment]
import pydivert
# Capture only TCP packets to port 80, i.e. HTTP requests.
w = pydivert.WinDivert("tcp.DstPort == 80 and tcp.PayloadLength > 0")
w.open()  # packets will be captured from now on
packet = w.recv()  # read a single packet
print(packet)
w.send(packet)  # re-inject the packet into the network stack
w.close()  # stop capturing packets

This is the piece of code, yes i checked in python lib as well all the .dll and .sys files are there

**Comment by Kaseaa** [comment]
Having the same issue as OP.

Python version - 3.6.8 64-bit (tried with 3.7.2 as well)
Operating System - Windows 10 64-bit

Code:
```python
import pydivert

# Capture only TCP packets to port 80, i.e. HTTP requests.
w = pydivert.WinDivert("tcp.DstPort == 80 and tcp.PayloadLength > 0")

w.open()  # packets will be captured from now on

packet = w.recv()  # read a single packet
print(packet)
w.send(packet)  # re-inject the packet into the network stack

w.close()  # stop capturing packets
```

Error:
```
C:\pydivert-test>python pydivert.py
Traceback (most recent call last):
  File "pydivert.py", line 1, in <module>
    import pydivert
  File "C:\pydivert-test\pydivert.py", line 4, in <module>
    with pydivert.WinDivert() as w:
AttributeError: module 'pydivert' has no attribute 'WinDivert'
```

**Comment by JacobFrye-1** [comment]
Seems like the __init__.py in your pydivert folder got corrupted somehow. It was the only way I could reproduce the error...If you did anything special then pls tell. Try replacing with __init__.py the one in the master and see if the issue persists.
